"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var main_1 = require("./src/main");
var main = new main_1.Main();
// console.log(main.getStudentBySchoolNum(12));
// console.log(main.getTeacherBySchoolNum(5));
// console.log(main.getStudentByGroup("9-V"));
// console.log(main.getTeacherByPredmet("MATEMATIKA"));
// console.log(main.getSchoolByNum(12));
console.log(main.getPredmetByTeacher("Lola"));
