"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const student_1 = require("./students/student/student");
const studentservice_1 = require("./students/student.service/studentservice");
const teacher_1 = require("./teachers/teacher/teacher");
const teacherservice_1 = require("./teachers/teacherservice/teacherservice");
let teacherService = new teacherservice_1.TeacherService();
let studentService = new studentservice_1.StudentService();
let teacher = new teacher_1.Teacher("Lola Azimova", 2, [12, 5, 73], "MATEMATIKA");
let student = new student_1.Student("Diyorbek Abdulhamdov", "900104240", "9-V", "Lola Azimova", 12);
teacherService.create(teacher);
studentService.create(student);
console.log(teacherService.getAllteachers());
console.log(studentService.getAllStudents());
